sudo: false
language: android
android:
  components:
    - build-tools-23.0.3
    - android-23
    - android-22
    - android-19
before_install:
  - rm pom.xml
script:
  - ./setup_env.sh gradle
  - gradle clean
  - gradle build
  
